### ISSUE TITLE
Change user password

### ISSUE THREAD

**Issue by bedoz** [realodix/newt#105]
Hi guys,
there an issue i've found on user change password page.
this should not ask for current password, i cannot know user password when i need to change it, this field must be removed.

Thanks
Alex

**Comment by realodix** [comment]
Hi Alex,

As you can see here [/app/Http/Controllers/Backend/User/ChangePasswordController.php#L36](https://github.com/realodix/newt/blob/master/app/Http/Controllers/Backend/User/ChangePasswordController.php#L36)

You just fill the field with your own password
