### ISSUE TITLE
error when going to admin 

### ISSUE THREAD

**Issue by tonyxhepa** [realodix/newt#155]
Argument 1 passed to App\Helpers\NumHlp::readable_int() must be of the type int, float given, called in C:\xampp\htdocs\blog\app\Helpers\Helpers.php on line 79 (View: C:\xampp\htdocs\blog\resources\views\backend\partials\stat.blade.php) (View: C:\xampp\htdocs\blog\resources\views\backend\partials\stat.blade.php)

**Comment by realodix** [comment]
In my env it's no problem. I need more info, how do you get that problem? Can you tell me specifically?

**Comment by realodix** [comment]
How can you get a float value?

**Comment by tonyxhepa** [comment]
when login as admin and go to dashboard have error

**Comment by realodix** [comment]
Fresh install with default config ([/config/newt.php](https://github.com/realodix/newt/blob/master/config/newt.php)) value?
