### ISSUE TITLE
Error When Composer Install

### ISSUE THREAD

**Issue by MaheKarim** [realodix/newt#169]
> In Application.php line 965:
>                                                                                 
>   The Mix manifest does not exist. See https://github.com/realodix/newt#compiling-assets-with-laravel-mix
>                                                                                 
> 
> Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

**Its Showing me when i hit composer install command.**

**Comment by progcode** [comment]
#meetoo

**Comment by MaheKarim** [comment]
> #metoo

You have to first install npm and then try but If you use Windows you will get Laravel 1071 Error.

**Comment by realodix** [comment]
Hi, 
I have already fixed this in https://github.com/realodix/newt/pull/173. There should be no error messages anymore.
